'''
A file where you store constants, please keep variable all UPPERCASE for formatting
'''

PERMISSION_GLOBAL_OWNER = 1
PERMISSION_GLOBAL_MEMBER = 2

PERMISSION_LOCAL_OWNER = 1
PERMISSION_LOCAL_MEMBER = 2

REACT_THUMBS_UP_ID = 1

PORT_NUMBER = 54321


USER_IN_CHANNEL = 1
USER_NOT_IN_CHANNEL = 0
